# **Part 1: Theoretical Question**
## ANSWER 1
TensorFlow Data Structures:
TensorFlow provides various data structures to represent and manipulate data, mainly for numerical computations in deep learning and machine learning. Some of the key data structures used in TensorFlow include:
1. Tensor: The fundamental data structure in TensorFlow is a tensor. Tensors are multi-dimensional arrays that can hold data of various data types. They are used to represent both input data and intermediate values in a computation graph. Tensors can have different ranks, such as scalars (0D tensors), vectors (1D tensors), matrices (2D tensors), and so on. Example:

In [11]:
import tensorflow as tf
scalar_tensor = tf.constant(5.0)  # 0D tensor (scalar)
vector_tensor = tf.constant([1, 2, 3])  # 1D tensor (vector)
matrix_tensor = tf.constant([[1, 2], [3, 4]])  # 2D tensor (matrix)

2. Variable: TensorFlow variables are used to represent mutable and trainable parameters in a neural network. They can be updated during training through gradient descent or other optimization algorithms. Example:

In [12]:
weight_variable = tf.Variable(initial_value=tf.random.normal((3, 3)))

Placeholder (Deprecated in TensorFlow 2.x): Placeholders were used in TensorFlow 1.x to feed data into the computation graph during training. In TensorFlow 2.x, placeholders have been replaced with tf.data and tf.data.Dataset for improved performance and flexibility.

## ANSWER 2
Constant: A TensorFlow constant is a fixed value that doesn't change during the execution of a computation graph. It is typically used for representing fixed data like hyperparameters, input data, or constants within the model.

In [13]:
constant_value = tf.constant(5.0)  # Creating a constant tensor

Variable: A TensorFlow variable, on the other hand, is a mutable tensor that can change its value during training. Variables are typically used to represent model parameters, such as weights and biases, that need to be updated during optimization.

In [14]:
initial_weights = tf.random.normal((3, 3))
weight_variable = tf.Variable(initial_value=initial_weights)  # Creating a variable

The key difference is update the value of a variable using operations like assign or during training, whereas a constant remains fixed throughout the execution.

## ANSWER 3
Matrix Operations in TensorFlow:

1. Matrix Addition: Add two matrices in TensorFlow using the tf.add or the + operator.

In [15]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.add(matrix_a, matrix_b)  # or result = matrix_a + matrix_b

In [16]:
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]], dtype=int32)>

2. Matrix Multiplication: Matrix multiplication is performed using tf.matmul or the @ operator for TensorFlow 2.x.

In [17]:

matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix_a, matrix_b)  # or result = matrix_a @ matrix_b

In [18]:
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

3. Element-wise Operations: Element-wise operations are performed on corresponding elements of two tensors. For example, element-wise addition can be done using tf.add or +.

In [19]:
tensor_a = tf.constant([1, 2, 3])
tensor_b = tf.constant([4, 5, 6])
result = tf.add(tensor_a, tensor_b)  # or result = tensor_a + tensor_b

In [20]:
result

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

# **Part 2 : Practical Implementation**
## Task 1: Creating and Manipulating Matrices

In [21]:
matrix_a = tf.random.normal(shape=(2, 2), mean=0, stddev=1)
print("Matrix A:")
print(matrix_a)

Matrix A:
tf.Tensor(
[[-0.16557658 -0.6896139 ]
 [-0.49519864 -1.1163532 ]], shape=(2, 2), dtype=float32)


In [25]:
matrix_b = tf.random.truncated_normal(shape=(2, 2), mean=0, stddev=1)
print("Matrix B:")
print(matrix_b)

Matrix B:
tf.Tensor(
[[-1.3972323   0.98763525]
 [ 1.7990675   0.8263609 ]], shape=(2, 2), dtype=float32)


In [26]:
mean = 2.0
stddev = 0.5  # Replace 'x' with the desired standard deviation
matrix_c = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("Matrix C:")
print(matrix_c)

Matrix C:
tf.Tensor(
[[1.830752  2.3653717]
 [2.0955818 2.3558764]], shape=(2, 2), dtype=float32)


In [27]:
matrix_d = tf.add(matrix_a, matrix_b)
print("Matrix D (result of addition):")
print(matrix_d)

Matrix D (result of addition):
tf.Tensor(
[[-1.5628089   0.29802138]
 [ 1.3038689  -0.28999227]], shape=(2, 2), dtype=float32)


In [28]:
matrix_e = tf.matmul(matrix_c, matrix_d)
print("Matrix E (result of multiplication):")
print(matrix_e)

Matrix E (result of multiplication):
tf.Tensor(
[[ 0.22301912 -0.14033628]
 [-0.20323992 -0.05865782]], shape=(2, 2), dtype=float32)


## Task 2: Performing Additional Matrix Operation

In [29]:
matrix_f = tf.random.uniform(shape=(2, 2), minval=0, maxval=1)
print("Matrix F:")
print(matrix_f)

Matrix F:
tf.Tensor(
[[0.24540067 0.8567823 ]
 [0.6777413  0.23086464]], shape=(2, 2), dtype=float32)


In [30]:
matrix_g = tf.transpose(matrix_f)
print("Matrix G (transpose of F):")
print(matrix_g)

Matrix G (transpose of F):
tf.Tensor(
[[0.24540067 0.6777413 ]
 [0.8567823  0.23086464]], shape=(2, 2), dtype=float32)


In [31]:
matrix_h = tf.exp(matrix_f)
print("Matrix H (element-wise exponential of F):")
print(matrix_h)

Matrix H (element-wise exponential of F):
tf.Tensor(
[[1.2781333 2.3555691]
 [1.9694244 1.2596887]], shape=(2, 2), dtype=float32)


In [32]:
matrix_i = tf.concat([matrix_f, matrix_g], axis=1)
print("Matrix I (concatenation of F and G horizontally):")
print(matrix_i)

Matrix I (concatenation of F and G horizontally):
tf.Tensor(
[[0.24540067 0.8567823  0.24540067 0.6777413 ]
 [0.6777413  0.23086464 0.8567823  0.23086464]], shape=(2, 4), dtype=float32)


In [33]:
matrix_j = tf.concat([matrix_f, matrix_h], axis=0)
print("Matrix J (concatenation of F and H vertically):")
print(matrix_j)

Matrix J (concatenation of F and H vertically):
tf.Tensor(
[[0.24540067 0.8567823 ]
 [0.6777413  0.23086464]
 [1.2781333  2.3555691 ]
 [1.9694244  1.2596887 ]], shape=(4, 2), dtype=float32)
